export const ADD_TO_QUEUE = 'QUEUE/ADD_TO_QUEUE';
export const PREPEND_TO_QUEUE = 'QUEUE/PREPEND_TO_QUEUE';
export const PLAY_TRACK = 'QUEUE/PLAY_TRACK';
export const NEXT_SONG = 'QUEUE/NEXT_SONG';
export const SET_ROOM_NAME = 'QUEUE/SET_ROOM_NAME';
export const POP_SONG = 'QUEUE/POP_SONG';
export const INSTANT_PLAY_TRACK = 'QUEUE/INSTANT_PLAY_TRACK';
export const PLAY_PAUSE_TRACK = 'QUEUE/PLAY_PAUSE_TRACK';